name: Tests d'intégration

on:
  push:
    branches:
      - main  # Remplacez par la branche principale de votre dépôt
  pull_request:
    branches:
      - main  # Remplacez par la branche principale de votre dépôt

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Remplacez par la version de .NET appropriée

      - name: Restaurer les packages
        run: dotnet restore

      - name: Build de l'application
        run: dotnet build --configuration Release

      - name: Exécuter les tests d'intégration
        run: dotnet test --configuration Release --filter FullyQualifiedName~IntegrationTest
